// Archivo: data.js
export const estadisticas = [
  {
    "codigo": "0101",
    "subtipo": "PRESUNTAS ACTIVIDADES CONTRA LA VIDA EL CUERPO Y LA SALUD",
    "enero": 2,
    "febrero": 7,
    "marzo": 11,
    "abril": 15,
    "mayo": 14,
    "junio": 13,
    "julio": 8,
    "agosto": 0
  },
  {
    "codigo": "0102",
    "subtipo": "PRESUNTA ACTIVIDAD CONTRA LA LIBERTAD",
    "enero": 2,
    "febrero": 2,
    "marzo": 3,
    "abril": 4,
    "mayo": 4,
    "junio": 4,
    "julio": 3,
    "agosto": 1
  },
  {
    "codigo": "0103",
    "subtipo": "PRESUNTAS ACTIVIDADES CONTRA EL PATRIMONIO",
    "enero": 10,
    "febrero": 23,
    "marzo": 20,
    "abril": 14,
    "mayo": 9,
    "junio": 11,
    "julio": 15,
    "agosto": 11
  },
  {
    "codigo": "0104",
    "subtipo": "PRESUNTAS ACTIVIDADES CONTRA LA SEG. PUB.",
    "enero": 1,
    "febrero": 3,
    "marzo": 27,
    "abril": 1,
    "mayo": 3,
    "junio": 3,
    "julio": 1,
    "agosto": 2
  },
  {
    "codigo": "0105",
    "subtipo": "PRE. ACTIV.CONTRA LA SALUD PUB.",
    "enero": 0,
    "febrero": 0,
    "marzo": 0,
    "abril": 0,
    "mayo": 0,
    "junio": 0,
    "julio": 8,
    "agosto": 0
  },
  {
    "codigo": "0106",
    "subtipo": "PRE. ACTIV. AMBIENTALES",
    "enero": 0,
    "febrero": 0,
    "marzo": 0,
    "abril": 0,
    "mayo": 0,
    "junio": 0,
    "julio": 0,
    "agosto": 0
  },
  {
    "codigo": "0107",
    "subtipo": "PRESUNTA ACTIVIDAD CONTRA LA TRANQUILIDAD PUB",
    "enero": 0,
    "febrero": 0,
    "marzo": 0,
    "abril": 0,
    "mayo": 2,
    "junio": 0,
    "julio": 1,
    "agosto": 3
  },
  {
    "codigo": "0108",
    "subtipo": "PRESUNTAS ACTIV. CONTRA LA ADM. PUB.",
    "enero": 0,
    "febrero": 3,
    "marzo": 1,
    "abril": 3,
    "mayo": 3,
    "junio": 3,
    "julio": 1,
    "agosto": 0
  },
  {
    "codigo": "0109",
    "subtipo": "PRE. ACTIV. CONTRA LOS PODERES DEL ESTADO",
    "enero": 0,
    "febrero": 0,
    "marzo": 0,
    "abril": 0,
    "mayo": 0,
    "junio": 0,
    "julio": 0,
    "agosto": 0
  },
  {
    "codigo": "0201",
    "subtipo": "PRESUNTA ACTIV. CONTRA CONTRA LA PERSONA",
    "enero": 1,
    "febrero": 0,
    "marzo": 1,
    "abril": 3,
    "mayo": 3,
    "junio": 11,
    "julio": 5,
    "agosto": 8
  },
  {
    "codigo": "0202",
    "subtipo": "PRESUNTA ACTIV. CONTRA EL PATRIMONIO",
    "enero": 10,
    "febrero": 23,
    "marzo": 20,
    "abril": 14,
    "mayo": 9,
    "junio": 22,
    "julio": 15,
    "agosto": 2
  },
  {
    "codigo": "0203",
    "subtipo": "PRE. ACTIV. CONTRA LA SEG. PÚBLICA",
    "enero": 0,
    "febrero": 0,
    "marzo": 0,
    "abril": 0,
    "mayo": 0,
    "junio": 0,
    "julio": 0,
    "agosto": 652
  },
  {
    "codigo": "0204",
    "subtipo": "PRESUNTA ACTIV. CONTRA LAS BUENAS COSTUMBRES",
    "enero": 34,
    "febrero": 49,
    "marzo": 27,
    "abril": 40,
    "mayo": 20,
    "junio": 29,
    "julio": 25,
    "agosto": 31
  },
  {
    "codigo": "0205",
    "subtipo": "PRESUNTA ACTIV. CONTRA LA TRANQUIL. PUB.",
    "enero": 0,
    "febrero": 0,
    "marzo": 0,
    "abril": 0,
    "mayo": 0,
    "junio": 0,
    "julio": 0,
    "agosto": 2
  },
  {
    "codigo": "0301",
    "subtipo": "PRESUNTOS ACCIDENTES E INFRACCIONES AL TRÁNSITO Y TRANSPORTE",
    "enero": 128,
    "febrero": 107,
    "marzo": 143,
    "abril": 208,
    "mayo": 137,
    "junio": 143,
    "julio": 78,
    "agosto": 60
  },
  {
    "codigo": "0302",
    "subtipo": "PRESUNTA ACTIV. CONTRA LA LEY DE PROTEC. Y BIENESTAR ANIMAL",
    "enero": 238,
    "febrero": 238,
    "marzo": 296,
    "abril": 324,
    "mayo": 244,
    "junio": 142,
    "julio": 179,
    "agosto": 2
  },
  {
    "codigo": "0303",
    "subtipo": "PRESUNTA ACTIV. DE PERSONAS QUE AFECTAN TRANQUILIDAD Y EL ORDEN",
    "enero": 174,
    "febrero": 326,
    "marzo": 208,
    "abril": 273,
    "mayo": 215,
    "junio": 142,
    "julio": 201,
    "agosto": 210
  },
  {
    "codigo": "0304",
    "subtipo": "PRESUNTAS INFRACCIONES A LAS ORDENANZAS Y LICENCIAS MUNICIPALES",
    "enero": 4,
    "febrero": 2,
    "marzo": 12,
    "abril": 5,
    "mayo": 4,
    "junio": 2,
    "julio": 9,
    "agosto": 191
  },
  {
    "codigo": "0401",
    "subtipo": "AYUDA, AUXILIO Y RESCATE DE PERSONAS",
    "enero": 3,
    "febrero": 1,
    "marzo": 5,
    "abril": 7,
    "mayo": 2,
    "junio": 13,
    "julio": 2,
    "agosto": 87
  },
  {
    "codigo": "0402",
    "subtipo": "APOYO A OTRAS GERENCIAS O AREAS DE LA MUNICIPALIDAD",
    "enero": 28,
    "febrero": 26,
    "marzo": 21,
    "abril": 13,
    "mayo": 19,
    "junio": 3,
    "julio": 3,
    "agosto": 2
  },
  {
    "codigo": "0403",
    "subtipo": "APOYO A OTRAS ENTIDADES",
    "enero": 7,
    "febrero": 13,
    "marzo": 11,
    "abril": 5,
    "mayo": 5,
    "junio": 18,
    "julio": 8,
    "agosto": 0
  },
  {
    "codigo": "0501",
    "subtipo": "DESASTRES",
    "enero": 4,
    "febrero": 12,
    "marzo": 12,
    "abril": 21,
    "mayo": 11,
    "junio": 23,
    "julio": 29,
    "agosto": 7
  },
  {
    "codigo": "0502",
    "subtipo": "INFRAESTRUCTURA Y SERVICIOS ESENCIALES AFECTADOS",
    "enero": 0,
    "febrero": 0,
    "marzo": 0,
    "abril": 0,
    "mayo": 0,
    "junio": 0,
    "julio": 0,
    "agosto": 17
  },
  {
    "codigo": "0503",
    "subtipo": "ESPACIOS PÚBLICOS EN RIESGO",
    "enero": 0,
    "febrero": 0,
    "marzo": 0,
    "abril": 0,
    "mayo": 0,
    "junio": 0,
    "julio": 0,
    "agosto": 10
  },
  {
    "codigo": "0601",
    "subtipo": "PRESUNTOS ACONTECIMIENTOS ESPECIALES",
    "enero": 4,
    "febrero": 7,
    "marzo": 3,
    "abril": 3,
    "mayo": 1,
    "junio": 1,
    "julio": 1,
    "agosto": 1
  },
  {
    "codigo": "0701",
    "subtipo": "OPERATIVO MUNICIPAL",
    "enero": 148,
    "febrero": 94,
    "marzo": 312,
    "abril": 323,
    "mayo": 188,
    "junio": 205,
    "julio": 232,
    "agosto": 223
  },
  {
    "codigo": "0702",
    "subtipo": "ESTRATEGIAS Y OPERATIVOS ESPECIALES",
    "enero": 101,
    "febrero": 154,
    "marzo": 164,
    "abril": 82,
    "mayo": 120,
    "junio": 106,
    "julio": 63,
    "agosto": 83
  }
];

export const operativosData = [
    { mes: 'enero', brigada_canina: 79, escuadron_verde: 103, halcones: 14, serenazgo: 841, integrado: 0, convenio: 187 },
    { mes: 'febrero', brigada_canina: 79, escuadron_verde: 90, halcones: 46, serenazgo: 952, integrado: 0, convenio: 156 },
    { mes: 'marzo', brigada_canina: 79, escuadron_verde: 117, halcones: 35, serenazgo: 1054, integrado: 0, convenio: 215 },
    { mes: 'abril', brigada_canina: 7, escuadron_verde: 123, halcones: 44, serenazgo: 1810, integrado: 0, convenio: 214 },
    { mes: 'mayo', brigada_canina: 33, escuadron_verde: 25, halcones: 77, serenazgo: 1538, integrado: 0, convenio: 177 },
    { mes: 'junio', brigada_canina: 29, escuadron_verde: 56, halcones: 64, serenazgo: 1776, integrado: 0, convenio: 172 },
    { mes: 'julio', brigada_canina: 45, escuadron_verde: 60, halcones: 47, serenazgo: 1833, integrado: 0, convenio: 232 },
    { mes: 'agosto', brigada_canina: 0, escuadron_verde: 0, halcones: 0, serenazgo: 0, integrado: 0, convenio: 203 },
];

export const estadisticasDelitos = [
  {
    "tipo": "Administración pública (delito)",
    "enero": 20,
    "febrero": 12,
    "marzo": 18,
    "abril": 12,
    "mayo": 15,
    "junio": 18,
    "julio": 12,
    "agosto": 11
  },
  {
    "tipo": "Adolescente infractor de la ley penal",
    "enero": 0,
    "febrero": 1,
    "marzo": 0,
    "abril": 1,
    "mayo": 0,
    "junio": 0,
    "julio": 0,
    "agosto": 0
  },
  {
    "tipo": "Ambientales(delito)",
    "enero": 0,
    "febrero": 0,
    "marzo": 1,
    "abril": 0,
    "mayo": 0,
    "junio": 0,
    "julio": 0,
    "agosto": 0
  },
  {
    "tipo": "Contra la dignidad humana",
    "enero": 1,
    "febrero": 0,
    "marzo": 0,
    "abril": 0,
    "mayo": 0,
    "junio": 1,
    "julio": 0,
    "agosto": 0
  },
  {
    "tipo": "Faltas",
    "enero": 31,
    "febrero": 32,
    "marzo": 34,
    "abril": 27,
    "mayo": 20,
    "junio": 11,
    "julio": 13,
    "agosto": 9
  },
  {
    "tipo": "Familia (delito)",
    "enero": 9,
    "febrero": 3,
    "marzo": 4,
    "abril": 0,
    "mayo": 4,
    "junio": 4,
    "julio": 2,
    "agosto": 3
  },
  {
    "tipo": "Fe publica (delito)",
    "enero": 5,
    "febrero": 0,
    "marzo": 2,
    "abril": 1,
    "mayo": 1,
    "junio": 6,
    "julio": 3,
    "agosto": 1
  },
  {
    "tipo": "Honor (delito)",
    "enero": 0,
    "febrero": 2,
    "marzo": 1,
    "abril": 0,
    "mayo": 1,
    "junio": 0,
    "julio": 0,
    "agosto": 0
  },
  {
    "tipo": "Humanidad (delito)",
    "enero": 1,
    "febrero": 1,
    "marzo": 0,
    "abril": 0,
    "mayo": 0,
    "junio": 0,
    "julio": 0,
    "agosto": 0
  },
  {
    "tipo": "Ley 30096 delitos informáticos, modificada por la ley 30171",
    "enero": 66,
    "febrero": 83,
    "marzo": 77,
    "abril": 72,
    "mayo": 69,
    "junio": 54,
    "julio": 58,
    "agosto": 57
  },
  {
    "tipo": "Ley de violencia contra la mujer y grupos vulnerables",
    "enero": 321,
    "febrero": 262,
    "marzo": 272,
    "abril": 302,
    "mayo": 281,
    "junio": 279,
    "julio": 240,
    "agosto": 213
  },
  {
    "tipo": "Libertad (delito)",
    "enero": 72,
    "febrero": 59,
    "marzo": 61,
    "abril": 63,
    "mayo": 64,
    "junio": 41,
    "julio": 49,
    "agosto": 37
  },
  {
    "tipo": "Menor infractor de la ley penal",
    "enero": 3,
    "febrero": 1,
    "marzo": 3,
    "abril": 6,
    "mayo": 5,
    "junio": 9,
    "julio": 8,
    "agosto": 4
  },
  {
    "tipo": "Orden financiero y monetario (delito)",
    "enero": 0,
    "febrero": 2,
    "marzo": 0,
    "abril": 1,
    "mayo": 0,
    "junio": 0,
    "julio": 0,
    "agosto": 0
  },
  {
    "tipo": "Patrimonio (delito)",
    "enero": 429,
    "febrero": 376,
    "marzo": 367,
    "abril": 331,
    "mayo": 329,
    "junio": 301,
    "julio": 259,
    "agosto": 277
  },
  {
    "tipo": "Patrimonio cultural (delito)",
    "enero": 0,
    "febrero": 0,
    "marzo": 0,
    "abril": 0,
    "mayo": 0,
    "junio": 0,
    "julio": 0,
    "agosto": 1
  },
  {
    "tipo": "Seguridad pública (delito)",
    "enero": 76,
    "febrero": 63,
    "marzo": 77,
    "abril": 60,
    "mayo": 66,
    "junio": 72,
    "julio": 92,
    "agosto": 55
  },
  {
    "tipo": "Trafico ilícito de drogas",
    "enero": 5,
    "febrero": 5,
    "marzo": 2,
    "abril": 1,
    "mayo": 0,
    "junio": 0,
    "julio": 2,
    "agosto": 2
  },
  {
    "tipo": "Tranquilidad publica (delito)",
    "enero": 1,
    "febrero": 5,
    "marzo": 5,
    "abril": 2,
    "mayo": 3,
    "junio": 3,
    "julio": 5,
    "agosto": 2
  },
  {
    "tipo": "Vida, el cuerpo y la salud (delito)",
    "enero": 82,
    "febrero": 69,
    "marzo": 60,
    "abril": 64,
    "mayo": 65,
    "junio": 51,
    "julio": 49,
    "agosto": 45
  }
];